---
title: "Clinical data"
date: "`r Sys.Date()`"
author: "Rebecca Luise Knoll"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE)
```

```{r path and packages, include=FALSE}
setwd("/Users/rebecca/Documents/Forschung/Orkambi_Kids/Paper/DeepPheno_Luma-Iva")
getwd() 

# install and load all needed packages
library(pacman)
pacman::p_load(tidyverse, phyloseq, magrittr, janitor, microbiome, knitr, lubridate, naniar, stringr)
#remotes::install_version("Matrix", version = "1.4-1")

#renv::activate()
#renv::status()
#renv::snapshot()

#renv::restore()
#renv::dependencies()

#renv::history()

#renv::update()

sessionInfo()
```

# Load data
```{r load data}

data <- readRDS("/Users/rebecca/Documents/Forschung/Orkambi_Kids/Paper/DeepPheno_Luma-Iva/data/metadata_combined_031123.rds")

my_colors_id <- c("#C03728FF", "#919C4CFF", "#FD8F24FF", "#F5C04AFF", "#E68C7CFF", "#C3C377FF", "#4F5157FF", "#6F5438FF") # "#828585FF",

data$gender <- as_factor(data$gender)
data  <- data %>% 
  mutate(sex = case_when(gender==0 ~ "male", gender==1 ~ "female")) %>% 
  mutate(sex=as_factor(sex))
# filter per visit

data_v1 <- data %>% 
  filter(visit=="1")
data_v2 <- data %>% 
  filter(visit=="2")
data_v3 <- data %>% 
  filter(visit=="3")
data_v4 <- data %>% 
  filter(visit=="4")
data_v5 <- data %>% 
  filter(visit=="5")
data_v6 <- data %>% 
  filter(visit=="6")
data_v7 <- data %>% 
  filter(visit=="7")
data_v8 <- data %>% 
  filter(visit=="8")
data_v9 <- data %>% 
  filter(visit=="9")
```

# Cohort characteristics at baseline
```{r Cohort characteristics at baseline}
library(gtsummary)

baseline <- data_v1 %>% select(sex, age, bmi_zscore, pp_fev1, pp_fvc)
b_table <- baseline %>% tbl_summary(type = c( age = "continuous", bmi_zscore = "continuous", pp_fev1= "continuous", pp_fvc= "continuous"),missing="no")

baseline %>% tbl_summary(type = c( age = "continuous", bmi_zscore = "continuous", pp_fev1= "continuous", pp_fvc= "continuous"),missing="no")%>%
  as_gt() %>%
  gt::gtsave(filename = "baseline.docx")

summary(baseline$age)
```

# Cohort characteristics follow-up
```{r Cohort characteristics fu}
trial2 <- data %>% select(visit, sex, age, bmi_zscore, pp_fev1, pp_fvc)

summary(trial2$age)

trial2%>% tbl_summary(by=visit, type = c( age = "continuous", bmi_zscore = "continuous", pp_fev1= "continuous", pp_fvc= "continuous"), missing="no")%>%
  as_gt() %>%
  gt::gtsave(filename = "characteristics_allVisits.docx")

```

```{r overall statistics for all serum}

summary(lmerTest::lmer(ig_g ~ visit_wo8+ (1|id), data))
summary(lmerTest::lmer(GOT ~ visit_wo8 +(1|id), data))
summary(lmerTest::lmer(GPT ~ visit_wo8 +(1|id), data))
summary(lmerTest::lmer(calprotectin ~ visit +(1|id), data))
data$calprotectin
```


```{r correlation analysis}

summary(lmerTest::lmer(ig_g ~ sweatchloride_mmol_l + (1|id), data))

data %>% 
  ggplot(aes(sweatchloride_mmol_l, ig_g, color=id))+
  geom_point()+
  stat_smooth(method="lm", se = F)+
  scale_color_manual(values=my_colors_id)


data %>% 
  filter(visit=="4")

```

