---
title: "Figure 2: Systemic response"
author: "Rebecca L. Knoll"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r path and packages1, include=FALSE}
library(pacman)

pacman::p_load(tidyverse, magrittr, janitor, microbiome, knitr, naniar, phyloseq, 
               textshape, Biostrings, markdown, vegan, rstatix, gdata, tableone, ggpubr, microViz)

```

```{r run tidy script, include=FALSE}

ps_orkambi_work <- readRDS("~/Documents/Forschung/Orkambi_Kids/Paper/DeepPheno_Luma-Iva/data/ps_orkambi_trimmed.rds")
ps_orkambi_work_rel <- readRDS("~/Documents/Forschung/Orkambi_Kids/Paper/DeepPheno_Luma-Iva/data/ps_orkambi_trimmed_relative.rds")

```

### Preprocessing    
```{r prepare metadata, include=FALSE}
Metadata_filt_2_1_9 <- data.frame(sample_data(ps_orkambi_work))
Metadata_filt_2_1_9$total_reads <- sample_sums(ps_orkambi_work)

metadata_unique <- Metadata_filt_2_1_9[!duplicated(Metadata_filt_2_1_9[ , c("probe_id")]), ]

# check read count
seq_quali <- Metadata_filt_2_1_9  %>% 
  group_by(material) %>% 
  summarise(N = n(),
            min= min(total_reads),
            max= max(total_reads),
            iqr= IQR(total_reads),
            median=median(total_reads))


writexl::write_xlsx(seq_quali, "/Users/rebecca/Documents/Forschung/Orkambi_Kids/Paper/DeepPheno_Luma-Iva/16S_seq_quality.xlsx")

Metadata_filt_2_1_9  %>% 
  ggplot(aes(y=total_reads, x=material))+
  geom_boxplot()

#write_csv(metadata_unique, "/Users/rebecca/Documents/Forschung/Orkambi_Kids/Paper/DeepPheno_Luma-Iva/metadata_raw.csv")
# I have to add missing lung functions and sweat chlorides from id8, i do this directly in the generated csv and reload the file

metadata_complete <- read_delim("/Users/rebecca/Documents/Forschung/Orkambi_Kids/Paper/DeepPheno_Luma-Iva/data/metadata_complete.csv")
metadata_complete <- metadata_complete %>% 
  mutate(id_visit=paste(id, visit, sep="_")) %>% 
  mutate(sex=gender)

metadata_complete[metadata_complete  == 9999] <- NA # replace placeholders by the study team with NA
metadata_complete[metadata_complete  == 99999] <- NA
# combine with liver enzymes
liver_df <- readxl::read_excel("/Users/rebecca/Documents/Forschung/Orkambi_Kids/Paper/Liver_enzymes_all.xlsx")

liver_df <- liver_df %>% 
  mutate(id_visit=paste(id, visit, sep="_")) %>% 
  select(id_visit, GOT,GPT)

metadata_complete <- metadata_complete%>% 
  left_join(liver_df, by="id_visit")

# add ig_g response
# igg_response
# 0 = bad
# 1 = good

metadata_complete <- metadata_complete %>%
   mutate(igg_response = case_when(id == 2 | id == 3 | id == 4 ~ FALSE,
                                 TRUE ~ TRUE)) %>%
   relocate(igg_response, .before = base)

# As id 8 is often the only participant with a V8 and that ruins visualization I will create a new variable where V8 is V9
metadata_complete <- metadata_complete%>%
  mutate(visit = case_when(visit == 8~9, TRUE~visit))

metadata_complete <- metadata_complete%>%
  mutate(baseline_ppfev1 = case_when(visit == 1 ~ pp_fev1))%>%
  group_by(id)%>%
  fill(baseline_ppfev1)%>%
  mutate(delta_ppfev1 = pp_fev1-baseline_ppfev1)%>%
  ungroup()

metadata_complete %>% 
  tabyl(id, visit)

```

```{r adjust metadata complete classes}
metadata_complete <- metadata_complete %>% 
  mutate(id=as_factor(id)) %>% 
  mutate(visit=as_factor(visit)) %>% 
  mutate(material=as_factor(material)) %>% 
  mutate(visit=as_factor(visit))
```

# Figure 1 systemic responses
```{r systemic responses}
my_colors_id <- c("#C03728FF", "#919C4CFF", "#FD8F24FF", "#F5C04AFF", "#E68C7CFF", "#C3C377FF", "#4F5157FF" ,"#6F5438FF")
# sweat chloride
p1 <- metadata_complete %>%
  filter(visit%in% c("1","2","5")) %>% 
  ggplot(aes(x=visit, y=sweatchloride_mmol_l)) +
  theme_minimal()+
  geom_point(aes(color = as_factor(id)), size=2.5) +
  geom_line(aes(x = visit, group = as_factor(id), color = as_factor(id),alpha=0.7), size=3) +
  geom_boxplot(aes(alpha=0.7), outlier.colour = NA) +
  ylab("Sweat chloride (mmol/l)")+
  theme(text = element_text(size=16), legend.position = "left",legend.margin = margin(50, 50, 50, 50), legend.key.size = unit(2, "lines"),  # Adjust the size of legend keys
           legend.text = element_text(size = 14)) +
  guides(alpha = FALSE)+
  scale_color_manual(name = "id", values = my_colors_id)+
  scale_x_discrete(labels = c("0", "3", "12"))+ # Custom x-axis labels
  xlab("months of treatment")
p1

# Inflammation 
p2 <- metadata_complete %>%
  filter(!is.na(ig_g), visit != "6", visit!="8") %>%  # Remove rows with NA in ig_g
  ggplot(aes(x = visit, y = ig_g)) +
  theme_minimal()+
  geom_point(aes(color = as_factor(id)), size=2.5) +
  geom_line(aes(x = visit, group = as_factor(id), color = as_factor(id),alpha=0.7), size=3) +
  geom_boxplot(aes(alpha=0.7), outlier.colour = NA) +
  ylab("IgG (g/l)") +
  xlab("visit") +
  theme(text = element_text(size = 16), legend.position = "none") +
  scale_color_manual(name = "id", values = my_colors_id) +
  scale_y_log10()+
  scale_x_discrete(labels = c("0", "3", "6", "9", "12", "18", "24*"))+ # Custom x-axis labels
  xlab("months of treatment")


p3 <- metadata_complete%>%
  filter(!is.na(leukos), visit!="6") %>% 
  ggplot(aes(x=visit, y= leukos)) +
  theme_minimal()+
  geom_point(aes(color = as_factor(id)), size=2.5) +
  geom_line(aes(x = visit, group = as_factor(id), color = as_factor(id),alpha=0.7), size=3) +
  geom_boxplot(aes(alpha=0.7), outlier.colour = NA) +
  ylab("Leucocytes /nl")+
  xlab("visit")+
  theme(text = element_text(size=16), legend.position = "none") +
  scale_color_manual(name = "id", values = my_colors_id)+
  scale_y_log10()+
  scale_x_discrete(labels = c("0", "3", "6", "9", "12", "18", "24*"))+ # Custom x-axis labels
  xlab("months of treatment")

 # Metabolome
# load Metabolome figures from Metabolome script via loadRDS
p4 <- readRDS("/Users/rebecca/Documents/Forschung/Orkambi_Kids/Paper/DeepPheno_Luma-Iva/Ivacaftor_RP_pos.rds")
p5 <- readRDS("/Users/rebecca/Documents/Forschung/Orkambi_Kids/Paper/DeepPheno_Luma-Iva/Tryptophan_RP_neg.rds")

p4 <- p4 +
  geom_point(aes(color = as_factor(id)), size=2.5) +
  geom_line(aes(x = visit, group = as_factor(id), color = as_factor(id),alpha=0.7), size=3) +
  #geom_text(aes(label = as_factor(id)))+ 
  geom_boxplot(aes(alpha=0.7), outlier.colour = NA) +
  ylab("Ivacaftor (MS Intensity)")+
  xlab("visit")+
  theme_minimal()+
  theme(text = element_text(size=16), legend.position = "none") +
  scale_color_manual(name = "id", values = my_colors_id)+
  scale_x_discrete(labels = c("0", "3", "6", "9", "12", "18", "24"))+ # Custom x-axis labels
  xlab("months of treatment")
  
p5 <- p5+
  geom_point(aes(color = as_factor(id)), size=2.5) +
  geom_line(aes(x = visit, group = as_factor(id), color = as_factor(id),alpha=0.7), size=3) +
  #geom_text(aes(label = as_factor(id)))+ 
  geom_boxplot(aes(alpha=0.7), outlier.colour = NA) +
  ylab("Tryptophan (MS Intensity)")+
  xlab("visit")+
  theme_minimal()+
  theme(text = element_text(size=16), legend.position = "none") +
  scale_color_manual(name = "id", values = my_colors_id)+
  scale_x_discrete(labels = c("0", "3", "6", "9", "12", "18", "24"))+ # Custom x-axis labels
  xlab("months of treatment")

library(gridExtra)
legend <- cowplot::get_legend(p1)
grid.arrange(legend)

# Arrange the ggplot objects in a grid
grid_arranged <- grid.arrange(
  legend,
  p1 + labs(tag = "a") + theme(legend.position = "none"), #margin = margin(25, 25, 25, 25), legend.box.spacing = unit(0, units = "pt"), legend.box.margin = margin(0, 0, 0, 0)
  p2 + labs(tag = "b"),
  p3 + labs(tag = "c"),
  p4 + labs(tag = "d"),
  p5 + labs(tag = "e"),
  ncol = 5, nrow = 2,
  widths = c(0.3, 0.2, 0.2, 0.2,0.2),
  layout_matrix = rbind(c(1, 3, 3, 4, 4),
                        c(2, 5, 5, 6, 6)
))

# Print or save the arranged plot
print(grid_arranged)

ggsave(plot=grid_arranged, "~/Documents/Forschung/Orkambi_Kids/Paper/DeepPheno_Luma-Iva/system_fig.pdf",dpi = 600, width = 12, height = 8)

```

# Statistics
```{r}
library(dplyr)
library(lmerTest)

# as we do not have visit 6 and 8 blood measurements, I exclude those from the metadata:

metadata_complete_wo68 <- metadata_complete %>% 
  filter(visit!=6, visit!=8)

lm_stats_function <- function(data, variable_of_interest, label) {
  lm <- summary(lmerTest::lmer({{ variable_of_interest }} ~ visit + sex + age + (1|id), data = data))

  coefs <- data.frame(coef(lm))
  fdr <- p.adjust(coefs$Pr...t.., method = "fdr", n = nrow(coefs))

  lm_stats <- bind_cols(coefs, fdr) %>%
    mutate(p = Pr...t..) %>%
    mutate(fdr = ...6) %>%
    select(-c(Pr...t.., ...6)) %>%
    rownames_to_column() %>%
    mutate(Months_after_ETI_start = rowname) %>%
    mutate(Months_after_ETI_start = case_when(
      Months_after_ETI_start == "(Intercept)" ~ "Baseline (Intercept)",
      Months_after_ETI_start == "visit2" ~ "3",
      Months_after_ETI_start == "visit3" ~ "6",
      Months_after_ETI_start == "visit4" ~ "9",
      Months_after_ETI_start == "visit5" ~ "12",
      Months_after_ETI_start == "visit6" ~ "15",
      Months_after_ETI_start == "visit7" ~ "18",
      Months_after_ETI_start == "visit8" ~ "21",
      Months_after_ETI_start == "visit9" ~ "24",
      Months_after_ETI_start == "sex" ~ "sex",
      Months_after_ETI_start == "age" ~ "age_y"
    )) %>%
    mutate(fdr_star = case_when(
      fdr <= 0.001 ~ "***",
      fdr <= 0.01 ~ "**",
      fdr <= 0.05 ~ "*",
      fdr <= 0.1 ~ ".",
      fdr >= 0.1 ~ "ns"
    )) %>%
    select(-rowname) %>%
    select(Months_after_ETI_start, Estimate, Std..Error, df, t.value, p, fdr, fdr_star) %>%
    mutate(p = round(p, 5)) %>%
    mutate(fdr = round(fdr, 5))


# Print lm stats into data frame and add N of observations
  nobs_per_visit <- data %>%
    filter(!is.na({{ variable_of_interest }})) %>% 
    group_by(visit) %>%
    summarise(N_obs = n()) %>% 
    mutate(Months_after_ETI_start = case_when(
      visit == "1" ~ "Baseline (Intercept)",
      visit == "2" ~ "3",
      visit == "3" ~ "6",
      visit == "4" ~ "9",
      visit == "5" ~ "12",
      visit == "6" ~ "15",
      visit == "7" ~ "18",
      visit == "8" ~ "21",
      visit == "9" ~ "24"
    )) %>% 
    mutate(Total_N_obs = sum(N_obs)) %>% 
    select(-visit)

  # Merge the two data frames
  lmm <- left_join(lm_stats, nobs_per_visit, by = "Months_after_ETI_start") 
  lmm$variable <-  label # Add variable of interest to dataframe
  lmm <- lmm %>% 
    select(variable, everything())
  return(lmm)
}

# Usage
sweat_stats <- lm_stats_function(metadata_complete_wo68, metadata_complete_wo68$sweatchloride_mmol_l, "Sweat chloride [mmol/l]")
sweat_stats

igg_stats <- lm_stats_function(metadata_complete_wo68, metadata_complete_wo68$ig_g, "IgG [g/l]")
igg_stats

leuko_stats <- lm_stats_function(metadata_complete_wo68, metadata_complete_wo68$leukos, "Leukocytes [/nl]")
leuko_stats

bsg_stats <- lm_stats_function(metadata_complete_wo68, metadata_complete_wo68$bsg_1h_mm, "BSG [mm/1h]")
bsg_stats

ige_stats <- lm_stats_function(metadata_complete_wo68, metadata_complete_wo68$ig_e, "IgE [g/l]")
ige_stats

crp_stats <- lm_stats_function(metadata_complete_wo68, metadata_complete_wo68$crp, "CRP [mg/l]")
crp_stats

# combine stats table
systemic_stats <- rbind(sweat_stats, igg_stats, leuko_stats, bsg_stats, ige_stats, crp_stats)

write_csv(systemic_stats, "/Users/rebecca/Documents/Forschung/Orkambi_Kids/Paper/Suppl_tables/st2_systemic_responses_stats.csv")

```

```{r}
sessionInfo()
```